export const BUY_POKEMON='BUY_POKEMON';
export const RETURN_POKEMON='RETURN_POKEMON';

export const FETCH_POKEMON_REQUEST='FETCH_POKEMON_REQUEST'
export const FETCH_POKEMON_SUCCESS='FETCH_POKEMON_SUCCESS'
export const FETCH_POKEMON_FAILURE='FETCH_POKEMON_FAILURE'
